### ISSUE TITLE
Setting the ssid and password

### ISSUE THREAD

**Issue by Shubhankar-Nath** [ARKK-Abhi1/C-Programming#1]
What if I enter a realy short or long string for the ssid and password? What if the string starts with a number?

**Comment by abhishekbisht1429** [comment]
I have made a few changes to the code. I have set the constraints for SSID and password length. If the user enters a string with characters more than the limit then an error message is displayed.
Further if the ssid starts with a number or any other invalid character then again an error message is shown....
In case of password the string can start with any character so there is no need to check wheter the first character of the string is alphabet or not.
